### ISSUE TITLE
Test suite task3 doesn't run on Windows.

### ISSUE THREAD

**Issue by akozeka** [BinaryStudioAcademy/bsa-2017-php-1#2]
Tests for task3 doesn't run on Windows because of Linux style usage for running PHP built-in server.

**Comment by m1x0n** [comment]
@akozeka , Thanks for pointing that. As a temporary suggestion: try to use virtual environment with Linux on board like https://laravel.com/docs/5.4/homestead.

We're going to release a patch soon.

**Comment by m1x0n** [comment]
@akozeka We attempted to resolve issue with running test cases for built in web-server in Windows env.
https://github.com/BinaryStudioAcademy/bsa-2017-php-1/pull/3

Check it out by pulling master branch.
